import Foundation
import SwiftUI

/// Orchestrates one voice therapy session:
/// mic → Cartesia STT → Claude → Cartesia TTS → speaker.
@MainActor
final class VoiceSessionViewModel: ObservableObject {
  enum State: Equatable {
    case connecting
    case idle        // ready, waiting for the user to tap and speak
    case listening   // capturing the user's turn
    case thinking    // transcribing + asking Claude
    case speaking    // playing Sonia's reply
    case error(String)
  }

  struct Line: Identifiable, Equatable {
    enum Speaker { case sonia, you }
    let id = UUID()
    let speaker: Speaker
    var text: String
  }

  @Published private(set) var state: State = .connecting
  @Published private(set) var statusText = "Connecting…"
  @Published private(set) var transcript: [Line] = []
  @Published private(set) var inputLevel: Float = 0
  /// Word-by-word caption that updates live as the user speaks (STT interim) and as
  /// Sonia speaks (TTS word timestamps synced to playback).
  @Published private(set) var liveCaption: String = ""
  /// Karaoke caption for Sonia's turn: the full spoken sentence (laid out dim from the
  /// start so the layout never reflows) and how many leading words are now "lit" as the
  /// audio reaches them.
  @Published private(set) var captionWords: [String] = []
  @Published private(set) var revealedWordCount: Int = 0
  @Published var permissionDenied = false

  // Live caption reveal state for the AI side (TTS karaoke).
  private var ttsWords: [String] = []
  private var ttsStarts: [Double] = []
  private var ttsAnchor: Date?

  // MARK: Hands-free turn-taking
  /// Whether the user granted the mic (asked once, on session entry).
  private var micGranted = false
  /// Silence-based endpointing: once the user has started speaking, a short trailing
  /// silence ends their turn automatically — no tap needed (phone-call feel).
  private var speechStarted = false
  private var lastVoiceAt: Date?
  /// RMS (0…1) above which we count the frame as speech.
  private let speechThreshold: Float = 0.12
  /// Trailing silence (seconds) after speech that ends the turn.
  private let endpointSilence: TimeInterval = 1.3

  private let audio = AudioSessionController()
  private let claude = ClaudeClient()
  private lazy var greetingGenerator = GreetingGenerator(claude: claude)
  private var currentSTT: CartesiaSTTClient?
  private var currentTTS: CartesiaTTSClient?
  private var history: [ClaudeClient.Turn] = []

  // MARK: Personalized memory (Phase 1 — read path)
  /// Therapist prompt + this user's memory context (without the per-session opening note).
  private var baseSystemPrompt = SoniaSystemPrompt.text
  /// `baseSystemPrompt` plus the just-spoken greeting note. Sent on every turn.
  private var systemPrompt = SoniaSystemPrompt.text
  private var memory: SoniaMemoryContext?
  private var firstName: String?
  private var timezoneIdentifier: String?

  // MARK: Accumulating memory (Phase 2 — write path)
  private var journal = MemoryJournal.empty
  private var todayString = MemoryConsolidator.todayISO()

  // MARK: - Lifecycle

  func begin() async {
    audio.onCapture = { [weak self] data in
      self?.currentSTT?.sendAudio(data)
    }
    audio.onInputLevel = { [weak self] level in
      Task { @MainActor in self?.handleInputLevel(level) }
    }

    loadMemory()

    // Like a phone call: ask for the mic the moment the session opens, so that after the
    // greeting the user can simply start talking — no tap required.
    micGranted = await audio.requestPermission()
    if micGranted == false { permissionDenied = true }

    // Bring up the persistent full-duplex audio graph once, before the greeting plays.
    // (Playback + capture share this one engine for the whole call.)
    do {
      try audio.start()
    } catch {
      print("[Session] audio engine start failed: \(error)")
    }

    // Memory-aware opening line. Generated by Claude from the user's history so the
    // session continues where it left off ("yesterday you said…").
    let timeOfDay = TimeOfDay.current(timezoneIdentifier: timezoneIdentifier)
    let greeting = await greetingGenerator.make(
      memory: memory,
      firstName: firstName,
      timeOfDay: timeOfDay
    )

    // Keep the conversation coherent: tell Claude what it just opened with (instead of
    // adding an assistant turn first, which the Messages API rejects).
    systemPrompt = baseSystemPrompt + """


    You have just opened this session by saying: "\(greeting)"
    Continue naturally from the person's reply — do not greet again or repeat yourself.
    """

    await speak(greeting, asSonia: true)

    // Hand the turn to the user automatically (hands-free). If the mic was declined,
    // fall back to idle so the tap-to-talk control + permission alert still work.
    if micGranted {
      await startListening()
    } else {
      setIdle()
    }
  }

  /// Loads the user's persona/history and builds the memory-injected system prompt.
  /// Degrades to the generic prompt if the seed can't be loaded.
  private func loadMemory() {
    guard let seed = try? SeedStore.load() else {
      baseSystemPrompt = SoniaSystemPrompt.text
      systemPrompt = baseSystemPrompt
      return
    }
    firstName = seed.user.firstName
    timezoneIdentifier = seed.user.timezone
    todayString = seed.meta.today.isEmpty
      ? MemoryConsolidator.todayISO(timezoneIdentifier: seed.user.timezone)
      : seed.meta.today
    journal = MemoryStore.load()
    let context = SoniaMemoryContext.build(from: seed, journal: journal)
    memory = context
    baseSystemPrompt = SoniaSystemPrompt.text + "\n\n" + context.systemContext
    systemPrompt = baseSystemPrompt
  }

  func end() {
    currentSTT?.close()
    currentTTS?.cancel()
    audio.teardown()

    // Consolidate this conversation into durable memory in the background, so today's
    // session shows up in tomorrow's context. Detached + value-captured so it survives
    // this view model being torn down on navigation. Best-effort: failures are silent.
    let snapshot = history
    guard snapshot.contains(where: { $0.role == .user }) else { return }
    let consolidator = MemoryConsolidator(claude: claude)
    let currentJournal = journal
    let day = todayString
    Task.detached {
      let updated = await consolidator.consolidate(history: snapshot, into: currentJournal, today: day)
      MemoryStore.save(updated)
    }
  }

  // MARK: - Turn control

  /// Tap is now a manual override on top of the hands-free flow: tap to talk if we're
  /// idle, or tap to end your turn early while listening.
  func toggleMic() {
    switch state {
    case .idle:
      Task { await startListening() }
    case .listening:
      Task { await finishTurn() }
    default:
      break
    }
  }

  private func startListening() async {
    guard micGranted else {
      permissionDenied = true
      setIdle()
      return
    }

    let stt = CartesiaSTTClient()
    currentSTT = stt
    liveCaption = ""
    speechStarted = false
    lastVoiceAt = nil
    stt.onLiveTranscript = { [weak self] live in
      Task { @MainActor in
        guard let self, self.state == .listening else { return }
        self.liveCaption = live
      }
    }
    stt.connect()

    do {
      try audio.startCapturing()
      state = .listening
      statusText = "Listening…"
    } catch {
      state = .error("Couldn't start the microphone.")
      statusText = "Audio error"
    }
  }

  /// Mic level callback. Drives the meter and the silence-based endpointing: once the
  /// user has clearly started speaking, a short trailing silence auto-ends their turn.
  private func handleInputLevel(_ level: Float) {
    inputLevel = level
    guard state == .listening else { return }

    let now = Date()
    if level >= speechThreshold {
      speechStarted = true
      lastVoiceAt = now
    } else if speechStarted, let last = lastVoiceAt, now.timeIntervalSince(last) >= endpointSilence {
      speechStarted = false
      lastVoiceAt = nil
      Task { await finishTurn() }
    }
  }

  private func finishTurn() async {
    audio.stopCapturing()
    inputLevel = 0
    state = .thinking
    statusText = "Thinking…"

    let userText = await currentSTT?.finishAndGetTranscript() ?? ""
    currentSTT?.close()
    currentSTT = nil

    // Caught silence with no words (false trigger / dead air) — just keep listening.
    guard userText.isEmpty == false else {
      await resumeListeningOrIdle()
      return
    }

    transcript.append(Line(speaker: .you, text: userText))
    history.append(.init(role: .user, text: userText))

    do {
      let reply = try await claude.reply(system: systemPrompt, history: history)
      history.append(.init(role: .assistant, text: reply))
      await speak(reply, asSonia: true)
    } catch {
      state = .error("Sonia couldn't respond just now. Tap to try again.")
      statusText = "Connection issue"
      return
    }

    // Continuous conversation: hand the turn straight back to the user.
    await resumeListeningOrIdle()
  }

  /// After a turn, reopen the mic automatically (hands-free); fall back to idle if the
  /// mic isn't available so the tap control still works.
  private func resumeListeningOrIdle() async {
    if micGranted {
      await startListening()
    } else {
      setIdle()
    }
  }

  // MARK: - Speaking

  private func speak(_ text: String, asSonia: Bool) async {
    if asSonia {
      transcript.append(Line(speaker: .sonia, text: text))
    }

    // Prepare the karaoke caption — the whole sentence, all dim — BEFORE flipping to
    // `.speaking` so the view never flashes the fully-lit line. Words light up as the
    // audio reaches them, against this fixed layout (no reflow).
    liveCaption = ""
    ttsWords = []
    ttsStarts = []
    ttsAnchor = nil
    captionWords = text.split(separator: " ").map(String.init)
    revealedWordCount = 0

    state = .speaking
    statusText = "Sonia is speaking…"

    audio.startPlayback()
    audio.resetPlaybackClock()

    let tts = CartesiaTTSClient()
    currentTTS = tts
    tts.onTimestamps = { [weak self] words, starts in
      Task { @MainActor in self?.revealTTSWords(words, starts: starts) }
    }
    await tts.speak(text) { [weak self] chunk in
      Task { @MainActor in self?.markPlaybackStartedIfNeeded() }
      self?.audio.enqueueTTS(pcmS16LE: chunk)
    }
    currentTTS = nil

    // The WebSocket delivers audio faster than realtime, so `tts.speak` returns while
    // the speaker is still playing. Stay in `.speaking` until playback actually finishes
    // so the word-by-word caption reveal (scheduled against the playback clock) can run
    // to the end instead of being cut off by `setIdle()`.
    await waitForPlaybackToFinish()

    // Guarantee the whole line is lit once playback finishes (covers any missed words).
    if state == .speaking { revealedWordCount = captionWords.count }
  }

  /// Sleeps until the audio scheduled during this utterance has finished playing,
  /// measured from when playback started (`ttsAnchor`).
  private func waitForPlaybackToFinish() async {
    guard let anchor = ttsAnchor else { return }
    let remaining = audio.scheduledPlaybackSeconds - Date().timeIntervalSince(anchor)
    guard remaining > 0 else { return }
    try? await Task.sleep(nanoseconds: UInt64(remaining * 1_000_000_000))
  }

  /// Anchors the caption reveal clock to when audio actually starts playing.
  private func markPlaybackStartedIfNeeded() {
    if ttsAnchor == nil { ttsAnchor = Date() }
  }

  /// Schedules each word to appear at its audio start time, synced to playback.
  private func revealTTSWords(_ words: [String], starts: [Double]) {
    if ttsAnchor == nil { ttsAnchor = Date() }
    let anchor = ttsAnchor ?? Date()
    let base = ttsWords.count
    ttsWords.append(contentsOf: words)
    ttsStarts.append(contentsOf: starts)

    for offset in 0..<words.count {
      let index = base + offset
      let startSec = index < ttsStarts.count ? ttsStarts[index] : 0
      let delay = max(0, anchor.addingTimeInterval(startSec).timeIntervalSinceNow)
      Task { @MainActor [weak self] in
        try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
        guard let self, self.state == .speaking else { return }
        // Light leading words up to (and including) this one. Clamp to the displayed
        // sentence and stay monotonic so out-of-order timers never un-light a word.
        let lit = min(index + 1, self.captionWords.count)
        self.revealedWordCount = max(self.revealedWordCount, lit)
      }
    }
  }

  private func setIdle() {
    state = .idle
    statusText = "Tap to speak"
  }
}
