import Foundation
import SwiftUI

/// Orchestrates one voice therapy session:
/// mic → Cartesia STT → Claude → Cartesia TTS → speaker.
@MainActor
final class VoiceSessionViewModel: ObservableObject {
  enum State: Equatable {
    case connecting
    case idle        // ready, waiting for the user to tap and speak
    case listening   // capturing the user's turn
    case thinking    // transcribing + asking Claude
    case speaking    // playing Sonia's reply
    case error(String)
  }

  struct Line: Identifiable, Equatable {
    enum Speaker { case sonia, you }
    let id = UUID()
    let speaker: Speaker
    var text: String
  }

  @Published private(set) var state: State = .connecting
  @Published private(set) var statusText = "Connecting…"
  @Published private(set) var transcript: [Line] = []
  @Published private(set) var inputLevel: Float = 0
  @Published var permissionDenied = false

  private let audio = AudioSessionController()
  private let claude = ClaudeClient()
  private lazy var greetingGenerator = GreetingGenerator(claude: claude)
  private var currentSTT: CartesiaSTTClient?
  private var currentTTS: CartesiaTTSClient?
  private var history: [ClaudeClient.Turn] = []

  // MARK: Personalized memory (Phase 1 — read path)
  /// Therapist prompt + this user's memory context (without the per-session opening note).
  private var baseSystemPrompt = SoniaSystemPrompt.text
  /// `baseSystemPrompt` plus the just-spoken greeting note. Sent on every turn.
  private var systemPrompt = SoniaSystemPrompt.text
  private var memory: SoniaMemoryContext?
  private var firstName: String?
  private var timezoneIdentifier: String?

  // MARK: - Lifecycle

  func begin() async {
    audio.onCapture = { [weak self] data in
      self?.currentSTT?.sendAudio(data)
    }
    audio.onInputLevel = { [weak self] level in
      DispatchQueue.main.async { self?.inputLevel = level }
    }

    loadMemory()

    // Memory-aware opening line. Generated by Claude from the user's history so the
    // session continues where it left off ("yesterday you said…"). Mic permission is
    // still deferred to the first tap, so the call screen opens with just the greeting.
    let timeOfDay = TimeOfDay.current(timezoneIdentifier: timezoneIdentifier)
    let greeting = await greetingGenerator.make(
      memory: memory,
      firstName: firstName,
      timeOfDay: timeOfDay
    )

    // Keep the conversation coherent: tell Claude what it just opened with (instead of
    // adding an assistant turn first, which the Messages API rejects).
    systemPrompt = baseSystemPrompt + """


    You have just opened this session by saying: "\(greeting)"
    Continue naturally from the person's reply — do not greet again or repeat yourself.
    """

    await speak(greeting, asSonia: true)
    setIdle()
  }

  /// Loads the user's persona/history and builds the memory-injected system prompt.
  /// Degrades to the generic prompt if the seed can't be loaded.
  private func loadMemory() {
    guard let seed = try? SeedStore.load() else {
      baseSystemPrompt = SoniaSystemPrompt.text
      systemPrompt = baseSystemPrompt
      return
    }
    firstName = seed.user.firstName
    timezoneIdentifier = seed.user.timezone
    let context = SoniaMemoryContext.build(from: seed)
    memory = context
    baseSystemPrompt = SoniaSystemPrompt.text + "\n\n" + context.systemContext
    systemPrompt = baseSystemPrompt
  }

  func end() {
    currentSTT?.close()
    currentTTS?.cancel()
    audio.teardown()
  }

  // MARK: - Turn control

  func toggleMic() {
    switch state {
    case .idle:
      Task { await startListening() }
    case .listening:
      Task { await finishTurn() }
    default:
      break
    }
  }

  private func startListening() async {
    let granted = await audio.requestPermission()
    guard granted else {
      permissionDenied = true
      state = .error("Microphone access is needed for a voice session.")
      statusText = "Microphone access denied"
      return
    }

    let stt = CartesiaSTTClient()
    currentSTT = stt
    stt.connect()

    do {
      try audio.startCapturing()
      state = .listening
      statusText = "Listening… tap when you're done"
    } catch {
      state = .error("Couldn't start the microphone.")
      statusText = "Audio error"
    }
  }

  private func finishTurn() async {
    audio.stopCapturing()
    inputLevel = 0
    state = .thinking
    statusText = "Thinking…"

    let userText = await currentSTT?.finishAndGetTranscript() ?? ""
    currentSTT?.close()
    currentSTT = nil

    guard userText.isEmpty == false else {
      setIdle()
      return
    }

    transcript.append(Line(speaker: .you, text: userText))
    history.append(.init(role: .user, text: userText))

    do {
      let reply = try await claude.reply(system: systemPrompt, history: history)
      history.append(.init(role: .assistant, text: reply))
      await speak(reply, asSonia: true)
    } catch {
      state = .error("Sonia couldn't respond just now. Tap to try again.")
      statusText = "Connection issue"
      return
    }

    setIdle()
  }

  // MARK: - Speaking

  private func speak(_ text: String, asSonia: Bool) async {
    if asSonia {
      transcript.append(Line(speaker: .sonia, text: text))
    }
    state = .speaking
    statusText = "Sonia is speaking…"

    do {
      try audio.startPlayback()
    } catch {
      print("[Session] playback start failed: \(error)")
    }

    let tts = CartesiaTTSClient()
    currentTTS = tts
    await tts.speak(text) { [weak self] chunk in
      self?.audio.enqueueTTS(pcmS16LE: chunk)
    }
    currentTTS = nil
  }

  private func setIdle() {
    state = .idle
    statusText = "Tap to speak"
  }
}
