import Foundation
import SwiftUI

/// Orchestrates one voice therapy session:
/// mic → Cartesia STT → Claude → Cartesia TTS → speaker.
@MainActor
final class VoiceSessionViewModel: ObservableObject {
  enum State: Equatable {
    case connecting
    case idle        // ready, waiting for the user to tap and speak
    case listening   // capturing the user's turn
    case thinking    // transcribing + asking Claude
    case speaking    // playing Sonia's reply
    case error(String)
  }

  struct Line: Identifiable, Equatable {
    enum Speaker { case sonia, you }
    let id = UUID()
    let speaker: Speaker
    var text: String
  }

  @Published private(set) var state: State = .connecting
  @Published private(set) var statusText = "Connecting…"
  @Published private(set) var transcript: [Line] = []
  @Published private(set) var inputLevel: Float = 0
  /// Word-by-word caption that updates live as the user speaks (STT interim) and as
  /// Sonia speaks (TTS word timestamps synced to playback).
  @Published private(set) var liveCaption: String = ""
  @Published var permissionDenied = false

  // Live caption reveal state for the AI side (TTS karaoke).
  private var ttsWords: [String] = []
  private var ttsStarts: [Double] = []
  private var ttsAnchor: Date?

  private let audio = AudioSessionController()
  private let claude = ClaudeClient()
  private lazy var greetingGenerator = GreetingGenerator(claude: claude)
  private var currentSTT: CartesiaSTTClient?
  private var currentTTS: CartesiaTTSClient?
  private var history: [ClaudeClient.Turn] = []

  // MARK: Personalized memory (Phase 1 — read path)
  /// Therapist prompt + this user's memory context (without the per-session opening note).
  private var baseSystemPrompt = SoniaSystemPrompt.text
  /// `baseSystemPrompt` plus the just-spoken greeting note. Sent on every turn.
  private var systemPrompt = SoniaSystemPrompt.text
  private var memory: SoniaMemoryContext?
  private var firstName: String?
  private var timezoneIdentifier: String?

  // MARK: Accumulating memory (Phase 2 — write path)
  private var journal = MemoryJournal.empty
  private var todayString = MemoryConsolidator.todayISO()

  // MARK: - Lifecycle

  func begin() async {
    audio.onCapture = { [weak self] data in
      self?.currentSTT?.sendAudio(data)
    }
    audio.onInputLevel = { [weak self] level in
      DispatchQueue.main.async { self?.inputLevel = level }
    }

    loadMemory()

    // Memory-aware opening line. Generated by Claude from the user's history so the
    // session continues where it left off ("yesterday you said…"). Mic permission is
    // still deferred to the first tap, so the call screen opens with just the greeting.
    let timeOfDay = TimeOfDay.current(timezoneIdentifier: timezoneIdentifier)
    let greeting = await greetingGenerator.make(
      memory: memory,
      firstName: firstName,
      timeOfDay: timeOfDay
    )

    // Keep the conversation coherent: tell Claude what it just opened with (instead of
    // adding an assistant turn first, which the Messages API rejects).
    systemPrompt = baseSystemPrompt + """


    You have just opened this session by saying: "\(greeting)"
    Continue naturally from the person's reply — do not greet again or repeat yourself.
    """

    await speak(greeting, asSonia: true)
    setIdle()
  }

  /// Loads the user's persona/history and builds the memory-injected system prompt.
  /// Degrades to the generic prompt if the seed can't be loaded.
  private func loadMemory() {
    guard let seed = try? SeedStore.load() else {
      baseSystemPrompt = SoniaSystemPrompt.text
      systemPrompt = baseSystemPrompt
      return
    }
    firstName = seed.user.firstName
    timezoneIdentifier = seed.user.timezone
    todayString = seed.meta.today.isEmpty
      ? MemoryConsolidator.todayISO(timezoneIdentifier: seed.user.timezone)
      : seed.meta.today
    journal = MemoryStore.load()
    let context = SoniaMemoryContext.build(from: seed, journal: journal)
    memory = context
    baseSystemPrompt = SoniaSystemPrompt.text + "\n\n" + context.systemContext
    systemPrompt = baseSystemPrompt
  }

  func end() {
    currentSTT?.close()
    currentTTS?.cancel()
    audio.teardown()

    // Consolidate this conversation into durable memory in the background, so today's
    // session shows up in tomorrow's context. Detached + value-captured so it survives
    // this view model being torn down on navigation. Best-effort: failures are silent.
    let snapshot = history
    guard snapshot.contains(where: { $0.role == .user }) else { return }
    let consolidator = MemoryConsolidator(claude: claude)
    let currentJournal = journal
    let day = todayString
    Task.detached {
      let updated = await consolidator.consolidate(history: snapshot, into: currentJournal, today: day)
      MemoryStore.save(updated)
    }
  }

  // MARK: - Turn control

  func toggleMic() {
    switch state {
    case .idle:
      Task { await startListening() }
    case .listening:
      Task { await finishTurn() }
    default:
      break
    }
  }

  private func startListening() async {
    let granted = await audio.requestPermission()
    guard granted else {
      permissionDenied = true
      state = .error("Microphone access is needed for a voice session.")
      statusText = "Microphone access denied"
      return
    }

    let stt = CartesiaSTTClient()
    currentSTT = stt
    liveCaption = ""
    stt.onLiveTranscript = { [weak self] live in
      Task { @MainActor in
        guard let self, self.state == .listening else { return }
        self.liveCaption = live
      }
    }
    stt.connect()

    do {
      try audio.startCapturing()
      state = .listening
      statusText = "Listening… tap when you're done"
    } catch {
      state = .error("Couldn't start the microphone.")
      statusText = "Audio error"
    }
  }

  private func finishTurn() async {
    audio.stopCapturing()
    inputLevel = 0
    state = .thinking
    statusText = "Thinking…"

    let userText = await currentSTT?.finishAndGetTranscript() ?? ""
    currentSTT?.close()
    currentSTT = nil

    guard userText.isEmpty == false else {
      setIdle()
      return
    }

    transcript.append(Line(speaker: .you, text: userText))
    history.append(.init(role: .user, text: userText))

    do {
      let reply = try await claude.reply(system: systemPrompt, history: history)
      history.append(.init(role: .assistant, text: reply))
      await speak(reply, asSonia: true)
    } catch {
      state = .error("Sonia couldn't respond just now. Tap to try again.")
      statusText = "Connection issue"
      return
    }

    setIdle()
  }

  // MARK: - Speaking

  private func speak(_ text: String, asSonia: Bool) async {
    if asSonia {
      transcript.append(Line(speaker: .sonia, text: text))
    }
    state = .speaking
    statusText = "Sonia is speaking…"

    // Reset the karaoke reveal state for this utterance.
    liveCaption = ""
    ttsWords = []
    ttsStarts = []
    ttsAnchor = nil

    do {
      try audio.startPlayback()
    } catch {
      print("[Session] playback start failed: \(error)")
    }
    audio.resetPlaybackClock()

    let tts = CartesiaTTSClient()
    currentTTS = tts
    tts.onTimestamps = { [weak self] words, starts in
      Task { @MainActor in self?.revealTTSWords(words, starts: starts) }
    }
    await tts.speak(text) { [weak self] chunk in
      Task { @MainActor in self?.markPlaybackStartedIfNeeded() }
      self?.audio.enqueueTTS(pcmS16LE: chunk)
    }
    currentTTS = nil

    // The WebSocket delivers audio faster than realtime, so `tts.speak` returns while
    // the speaker is still playing. Stay in `.speaking` until playback actually finishes
    // so the word-by-word caption reveal (scheduled against the playback clock) can run
    // to the end instead of being cut off by `setIdle()`.
    await waitForPlaybackToFinish()

    // Guarantee the full line is shown once playback finishes (covers any missed words).
    if state == .speaking { liveCaption = text }
  }

  /// Sleeps until the audio scheduled during this utterance has finished playing,
  /// measured from when playback started (`ttsAnchor`).
  private func waitForPlaybackToFinish() async {
    guard let anchor = ttsAnchor else { return }
    let remaining = audio.scheduledPlaybackSeconds - Date().timeIntervalSince(anchor)
    guard remaining > 0 else { return }
    try? await Task.sleep(nanoseconds: UInt64(remaining * 1_000_000_000))
  }

  /// Anchors the caption reveal clock to when audio actually starts playing.
  private func markPlaybackStartedIfNeeded() {
    if ttsAnchor == nil { ttsAnchor = Date() }
  }

  /// Schedules each word to appear at its audio start time, synced to playback.
  private func revealTTSWords(_ words: [String], starts: [Double]) {
    if ttsAnchor == nil { ttsAnchor = Date() }
    let anchor = ttsAnchor ?? Date()
    let base = ttsWords.count
    ttsWords.append(contentsOf: words)
    ttsStarts.append(contentsOf: starts)

    for offset in 0..<words.count {
      let index = base + offset
      let startSec = index < ttsStarts.count ? ttsStarts[index] : 0
      let delay = max(0, anchor.addingTimeInterval(startSec).timeIntervalSinceNow)
      Task { @MainActor [weak self] in
        try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
        guard let self, self.state == .speaking, index < self.ttsWords.count else { return }
        self.liveCaption = self.ttsWords[0...index].joined(separator: " ")
      }
    }
  }

  private func setIdle() {
    state = .idle
    statusText = "Tap to speak"
  }
}
